# Generated by Django 5.1.1 on 2024-09-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
